#!/bin/sh -ue

# Requires: sed(1)

## mod_secdownload

# Usage: get_param <u> ...
get_param()
{
    local n="${0##*/mod/}"
    local u="${1:?missing 1st arg to ${n}() (<u>)}" && shift

    local secret

    # templ: secdownload_secret
    if secret="$(
        sed 2>/dev/null "$u/mod/$n" \
            -e '1!q;/^[^\"'\''\\&|]\{64\}$/!q;p' \
            -n \
            #
    )" && [ -n "$secret" ]; then
        :
    else
        # there is no default
        return
    fi

    echo "$secret"
}
get_param "$@"
