#!/bin/sh

# Build a certificate signing request and private key.  Use this
# when your root certificate and key is not available locally.

if [ -z "$IN_EXEC_CA" ]; then
	printf >&2 -- '%s: run with "exec-ca" prepared environment\n' "$0"
	exit 1
fi

# Source functions library
. "$EASY_RSA/easy-rsa-lib.sh"

exec "$EASY_RSA/pkitool" --interact --csr "$@"
