#!/bin/sh

# list revoked certificates

if [ -z "$IN_EXEC_CA" ]; then
	printf >&2 -- '%s: run with "exec-ca" prepared environment\n' "$0"
	exit 1
fi

# Source functions library
. "$EASY_RSA/easy-rsa-lib.sh"

cd "$KEY_DIR" && exec "$OPENSSL" crl -text -noout -in "${1:-crl.pem}"
